apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
spec:
 selector:
   matchLabels:
     app: nginx
 replicas: 2
 template:
   metadata:
     labels:
       app: nginx
   spec:
     containers:
     - name: nginx
       image: nginx:1.7.9
       ports:
       - containerPort: 80
       env:
       - name: DB_URL
         valueFrom:
           configMapKeyRef:
             name: db-config
             key: DB_URL
       - name: DB_ID
         valueFrom:
           configMapKeyRef:
             name: db-config
             key: DB_ID
       - name: DB_PWD
         valueFrom:
           secretKeyRef:
             name: db-secret
             key: DB_PWD