apiVersion: v1
kind: Pod
metadata:
 name: nginx
 namespace: my-ds
spec:
 containers:
 - name: nginx
   image: nginx
   resources:
     requests:
       cpu: "30m"
       memory: "30Mi"
     limits:
       cpu: "300m"
       memory: "300Mi"
   ports:
   - containerPort: 80